name: Deploy Images to GHCR

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
      docker:
        runs-on: ubuntu-latest
        steps:
          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v3
          - name: Login to ghcr.io 
            uses: docker/login-action@v3
            if: ${{ github.ref == 'refs/heads/main' }}
            with:
              registry: ghcr.io
              username: ${{github.actor}}
              password: ${{secrets.GITHUB_TOKEN}}
          - name: Build and push
            uses: docker/build-push-action@v5
            with:
              context: .