name: ci

env:
  REGISTRY: ghcr.io/kabot-io
  IMAGE_NAME: test

on:
  push:
    branches:
      - "main"

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      targets: ${{ steps.generate.outputs.targets }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: List targets
        id: generate
        uses: docker/bake-action/subaction/list-targets@v4
        with:
          target: default
          files: "kabot-containers.hcl"

  build:
    runs-on: ubuntu-latest
    needs:
      - prepare
    strategy:
      fail-fast: false
      matrix:
        target: ${{ fromJson(needs.prepare.outputs.targets) }}

    permissions:
      contents: read
      packages: write

    steps:
      - 
        name: Checkout
        uses: actions/checkout@v4
      - 
        name: Login to ghcr.io 
        uses: docker/login-action@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          registry: ghcr.io
          username: kabot-io
          password: ${{secrets.ROBOT_PAT}}
      - 
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - 
        name: Build and push
        uses: docker/bake-action@v4
        with:
          push: true
          targets: ${{ matrix.target }}
          files: "kabot-containers.hcl"

  run-ros:
    runs-on: ubuntu-latest
    needs:
      - prepare
      - build
    strategy:
      fail-fast: false
      matrix:
        target: ${{ fromJson(needs.prepare.outputs.targets) }}
    container:
      image: ghcr.io/kabot-io/${{ matrix.target }}:latest
    steps:
      -
        name: check ros installation
        run: bash -c "source /opt/ros/humble/setup.bash && ros2 pkg list" || (echo "Failed to run ros2" && exit 1)
